### PR TITLE
Comprehensive updates

### PR DESCRIPTION
**Pull request by dave-burke**
This PR does some comprehensive updates the project, mostly to migrate away from deprecated libraries and outdated versions.

- [x] Vue 2 -> Vue 3
- [x] Class based components -> Composition API
- [x] Vue CLI -> Vite
- [x] Vuex -> Pinia
- [x] BootstrapVue -> Vuetify
- [x] Find a replacement for "Toast" notifications
- [x] Update to the OpenWeather 3.0 API
- [x] Fix unit tests

This PR removes some features that we either haven't needed, are based on deprecated projects, or that I just don't have time to port:

- Codecept
- count api
- storybook

## Checklist before requesting approval

- [x] All PR checks succeed
- [x] This branch does not have any conflicts with the master branch.
- [x] The version number has been incremented appropriately (we use [Semver](https://semver.org/) as a versioning strategy).

### CODE REVIEW

**Comment by dave-burke** [comment]
@mjp2233 FYI the OpenWeather 2.5 API gets shut off tomorrow :grimacing:. I've been working on this off and on for a while, and it's just about ready to go. I've only been focused on getting all the dependencies and frameworks up to date, though. I haven't touched the `openWeatherService.ts` file. I think you said you started to look at that? I don't want to duplicate your efforts.

**Comment by mjp2233** [comment]
The only change I made was this [URL change from 2.5 to 3](https://github.com/skill-collectors/weather-app/blob/96afc021ef02ba63466b0095579d5556cb47c0c4/src/services/openWeatherService.ts#L8). I reviewed the change log regarding objects/fields related to the endpoint we use and didn't see anything that would impact us.

The other part is just [subscribing to the new v3 endpoint](https://openweathermap.org/one-call-transfer#how) which I believe required me to enter a form of payment, but the limit can be set below the threshold that would require paying anything.

**Comment by dave-burke** [comment]
@mjp2233 This is at a pretty good stopping point. I still need to fix the unit tests before we merge, but if there's anything you want to look at in the mean time the rest of it is ready for whatever kind of review you want to do.

**Comment by dave-burke** [comment]
@mjp2233 Oof, I think this is finally as done as it's going to be. Any objection to merging it? Feel free to pull the trigger if you think it's good to go!

**Pull request merged**
